config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    # get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

  resources :user do
    resources :notes do
      resources :workouts
    end
  end

  root to: 'home#index'
  get 'home/index'
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :note
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:note_id, :meter, :kcal, :steps, :sec, :memo)
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.slim
= form_for @workout do |f|
  - if @workout.errors.any?
    #error_explanation
      h2 = "#{pluralize(@workout.errors.count, "error")} prohibited this workout from being saved:"
      ul
        - @workout.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :note
    = f.text_field :note
  .field
    = f.label :meter
    = f.text_field :meter
  .field
    = f.label :kcal
    = f.text_field :kcal
  .field
    = f.label :steps
    = f.text_field :steps
  .field
    = f.label :sec
    = f.text_field :sec
  .field
    = f.label :memo
    = f.text_area :memo
  .actions = f.submit

app/views/workouts/edit.html.slim
h1 Editing workout

== render 'form'

=> link_to 'Show', @workout
'|
=< link_to 'Back', workouts_path

app/views/workouts/index.html.slim
h1 Listing workouts

table
  thead
    tr
      th Note
      th Meter
      th Kcal
      th Steps
      th Sec
      th Memo
      th
      th
      th

  tbody
    - @workouts.each do |workout|
      tr
        td = workout.note
        td = workout.meter
        td = workout.kcal
        td = workout.steps
        td = workout.sec
        td = workout.memo
        td = link_to 'Show', workout
        td = link_to 'Edit', edit_workout_path(workout)
        td = link_to 'Destroy', workout, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Workout', new_workout_path

app/views/workouts/new.html.slim
h1 New workout

== render 'form'

= link_to 'Back', workouts_path

app/views/workouts/show.html.slim
p#notice = notice

p
  strong Note:
  = @workout.note
p
  strong Meter:
  = @workout.meter
p
  strong Kcal:
  = @workout.kcal
p
  strong Steps:
  = @workout.steps
p
  strong Sec:
  = @workout.sec
p
  strong Memo:
  = @workout.memo

=> link_to 'Edit', edit_workout_path(@workout)
'|
=< link_to 'Back', workouts_path