config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    # get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

  resources :user do
    resources :notes do
      resources :workouts
    end
  end

  root to: 'home#index'
  get 'home/index'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:user_id, :date, :weather, :location, :physical_conditions, :diary)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.slim
= form_for @note do |f|
  - if @note.errors.any?
    #error_explanation
      h2 = "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      ul
        - @note.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :weather
    = f.number_field :weather
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :physical_conditions
    = f.number_field :physical_conditions
  .field
    = f.label :diary
    = f.text_area :diary
  .actions = f.submit

app/views/notes/edit.html.slim
h1 Editing note

== render 'form'

=> link_to 'Show', @note
'|
=< link_to 'Back', notes_path

app/views/notes/index.html.slim
h1 Listing notes

table
  thead
    tr
      th User
      th Date
      th Weather
      th Location
      th Physical conditions
      th Diary
      th
      th
      th

  tbody
    - @notes.each do |note|
      tr
        td = note.user
        td = note.date
        td = note.weather
        td = note.location
        td = note.physical_conditions
        td = note.diary
        td = link_to 'Show', note
        td = link_to 'Edit', edit_note_path(note)
        td = link_to 'Destroy', note, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Note', new_note_path

app/views/notes/new.html.slim
h1 New note

== render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.slim
p#notice = notice

p
  strong User:
  = @note.user
p
  strong Date:
  = @note.date
p
  strong Weather:
  = @note.weather
p
  strong Location:
  = @note.location
p
  strong Physical conditions:
  = @note.physical_conditions
p
  strong Diary:
  = @note.diary

=> link_to 'Edit', edit_note_path(@note)
'|
=< link_to 'Back', notes_path