config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    # get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

  resources :user do
    resources :notes do
      resources :workouts
    end
  end

  root to: 'home#index'
  get 'home/index'
end

app/views/shared/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand[href="#"]
    | Runote
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        a.nav-link[href="#"]
          | Home 
          span.sr-only
            | (current)
      li.nav-item
        a.nav-link[href="#"]
          | Link
      li.nav-item.dropdown
        a#navbarDropdown.nav-link.dropdown-toggle[href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
          |  Dropdown 
        .dropdown-menu[aria-labelledby="navbarDropdown"]
          a.dropdown-item[href="#"]
            | Action
          a.dropdown-item[href="#"]
            | Another action
          .dropdown-divider
          a.dropdown-item[href="#"]
            | Something else here
      li.nav-item
        a.nav-link.disabled[href="#" tabindex="-1" aria-disabled="true"]
          | Disabled

    - if  user_signed_in?
      = link_to 'Log Out', logout_path, class: 'btn btn-outline-success my-2 my-sm-0'
    - else
      = link_to 'Log In', login_path, class: 'btn btn-outline-success my-2 my-sm-0'